#### Christian Altrichter, Jury Andrea D'Onofrio, Francesco Huber

In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math



In [31]:

image1_points = [[285,410], 
                [415,271], 
                [483,277], 
                [608,62], 
                [750, 215], 
                [575,485],
                [410,60],
                [682,340],
                [278,245],
                [735, 392]]


image1_points2 = [[236,412], 
                [375,348], 
                [415,434], 
                [640,352], 
                [572, 252]
                ]


image2_points = [[285,446], 
                [344,290], 
                [375,295], 
                [690,75], 
                [806, 251], 
                [388,538],
                [341,59],
                [662,395],
                [285, 270],
                [792,482]]

image2_points2 = [[240,445], 
                [301,370], 
                [345,377], 
                [575,400], 
                [422, 259]
                ]

world_points = [
    [-1.0 ,-1.0, 0.0, 1.0],
    [0.015545, -1.0, 0.965257, 1.0],
    [0.491684, -1.0, 0.965257, 1.0],
    [0.0, 1.03586, 2.1009, 1.0],
    [1.05319, 1.03586, 1.15121, 1.0],
    [1.22323, -1.22323, 0.0, 1.0],
    [0.0, -1.0, 2.1009, 1.0],
    [1.0, 0.234552, 0.489472, 1.0],
    [-1.05319, -1.0, 1.0, 1.0],
    [1.0, 1.0, 0.0, 1.0]
    ]


In [ ]:
H = compute_homography_matrix

### Part 1

In [5]:
# Projection matrix P is a 3x4
F = projection_matrix(image1_points, image2_points)

print("Fundamental matrix F:")
print(F)

Fundamental matrix F:
[[-9.34959856e-04 -3.45539509e-04  8.37977628e-01]
 [-1.00246786e-03  6.68488142e-04  5.45697525e-01]
 [-2.99135687e-06 -2.24872125e-07  2.29379060e-03]]


### Part 2

In [1]:

P_hat = np.hstack((np.eye(3), np.zeros((3,1))))
print("P is", P_hat)

# Not entirely sure here
e = np.linalg.svd(F)[2][-1]
# From slides page 8
ex = [[0,-e[2],e[1]], 
      [e[2], 0, -e[0]],
      [-e[1],e[0], 0]]

print(ex)
# As per assignment instructions
P_hat_prime = np.hstack(((ex @ F),  np.zeros((3,1))))

print(P_hat_prime)

# As per book 12.2
def linear_triangulation(x, x_p, P, P_p):
    num_points = len(x)
    
    A = np.zeros([10, 4 * 4])
    print("A is", A)
    for i in range(num_points):
        
        A[i][0], A[i][1], A[i][2], A[i][3] = np.dot(x[i][0], P[2]) - P[0]
        A[i][4], A[i][5], A[i][6], A[i][7] = np.dot(x[i][1], P[2]) - P[1]
        A[i][8], A[i][8], A[i][10], A[i][11] = np.dot(x_p[i][0], P_p[2]) - P_p[0]
        A[i][12], A[i][13], A[i][14], A[i][15] = np.dot(x_p[i][1], P_p[2]) - P_p[1]
           
    _, _, V = np.linalg.svd(A)
    p = V[-1, :]
    print("p is", p)
    
    return A

NameError: name 'np' is not defined

In [115]:
A = linear_triangulation(image1_points, image2_points, P_hat, P_hat_prime)

A is [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
p is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
